### ISSUE TITLE
Shouldn't $parentId in SpanContext be optional?

### ISSUE THREAD

**Issue by stesie** [code-tool/jaeger-client-php#2]
Currently the constructor argument `$parentId` of `Jaeger\Span\Context\SpanContext` is required, as it is strictly declared `int`. Also `getParentId` has strict return type `int`.

Today I wanted to use `doctrine-jaeger-symfony-bridge` in a tracing-enabled Istio setup, which uses the default B3 propagation. According to the [B3 propagation spec](https://github.com/openzipkin/b3-propagation) the `X-B3-ParentSpanId` field is optional. And requests originating from Istio's ingressgateway are missing this particular header.
(so what I'm actually willing to do is writing a header extractor, that takes those headers from Symfony's request object and provide a `SpanContext` with only TraceId & SpanId set ... and register that service as `jaeger.context.extractor` in the DI container)

The rest of the jaeger-client-php implementation already handles `$parentId` being null well, especially `\Jaeger\Thrift\Span` already has a `$this->parentSpanId !== null` check in `write`.

Do you agree that both type hints should be changed from `int` to `?int` ... or am I completely off the tracks (I'm still pretty new to all the Istio/OpenTracing stuff)

**Comment by allflame** [comment]
@stesie As far as documentation goes, this is likely the case of the "root" span.
This us handled as spanId to be equal traceId and parentId to be equal 0 (and potentially null)
I think you (via PR) or we can make it nullable, changes nothing TBH.

**Comment by stesie** [comment]
oh, you're right. Setting it zero just works fine :-)
